import 'package:flutter/material.dart';
import 'package:darts_101/manage_players.dart';
import 'package:darts_101/manage_teams.dart';
import 'package:darts_101/game_selection.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:darts_101/database/player.dart';
import 'package:darts_101/database/team.dart';
import 'package:darts_101/database/game.dart';
import 'package:darts_101/database/gamescore.dart';
import 'package:darts_101/database/gamebuildup.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:flutter/foundation.dart';

void main() async {
  await Hive.initFlutter();
  
  Hive.registerAdapter(PlayerAdapter());      // Register the Player adapter generated by build_runner
  Hive.registerAdapter(TeamAdapter());        // Register the Team adapter generated by build_runner
  Hive.registerAdapter(GameAdapter());        // Register the Game adapter generated by build_runner  
  Hive.registerAdapter(GameScoreAdapter());   // Register the GameScore adapter generated by build_runner
  Hive.registerAdapter(GameBuildUpAdapter()); // Register the GameBuildUp adapter generated by build_runner

  final playersBox = await Hive.openBox<Player>('playersBox');  // Hive openBox playersBox for future use in other modules
  final teamsBox = await Hive.openBox<Team>('teamsBox');        // Hive openBox teamsBox for future use in other modules
  await Hive.openBox<Game>('gamesBox');                         // Hive openBox gamesBox for future use in other modules
  await Hive.openBox<GameScore>('gamescoresBox');               // Hive openBox gamescoresBox for future use in other modules
  await Hive.openBox<GameBuildUp>('gameTeamBuildUpBox');        // Hive openBox gamescoresBox for future use in other modules
  
  // Only seeds if we are in Debug Mode AND the database is empty
  if (kDebugMode) {
    // AutoFill for testing           
    if (playersBox.isEmpty){
      await _seedHiveDatabase(playersBox, teamsBox);
    }
  }

  // Do not delete, obligatoire pour que l'application fonctionne
  runApp(const MyApp());
}

Future<void> _seedHiveDatabase(Box<Player> playersBox, Box<Team> teamsBox) async {
  // seed Players
  List<Player> listPlayers = [
    Player(idPlayer: 0, firstName: 'Dominique', lastName: 'Goudreault', nickName: 'Domi', deleted: false),
    Player(idPlayer: 1, firstName: 'Éric', lastName: 'St-Pierre', nickName: 'Ricky', deleted: false),
    Player(idPlayer: 2, firstName: 'Christopher', lastName: 'Lafond', nickName: 'Christo', deleted: false),
    Player(idPlayer: 3, firstName: 'Frédéric', lastName: 'Gagnon', nickName: 'Marcel', deleted: false),
    Player(idPlayer: 4, firstName: 'Frederik', lastName: 'Peeters Bélanger', nickName: 'Fred', deleted: false),
    Player(idPlayer: 5, firstName: 'Simon', lastName: 'Drouin', nickName: 'Drou', deleted: false),
    Player(idPlayer: 6, firstName: 'Étienne', lastName: 'Lefrançois', nickName: 'Ti-ti', deleted: false),
    Player(idPlayer: 7, firstName: 'Marc-Olivier', lastName: 'Fortin', nickName: 'Marco', deleted: false),
    Player(idPlayer: 8, firstName: 'Ludovick', lastName: 'Gosselin', nickName: 'Ludo', deleted: false),
    Player(idPlayer: 9, firstName: 'Maxime', lastName: 'Gagnon', nickName: 'Max', deleted: false),
    Player(idPlayer: 10, firstName: 'Michel', lastName: 'Deschênes', nickName: 'Papy', deleted: false),
    Player(idPlayer: 11, firstName: 'Charles', lastName: 'Lirette', nickName: 'Marco', deleted: false),
    Player(idPlayer: 12, firstName: 'Kevin', lastName: 'Milonas', nickName: 'Milo', deleted: false),
  ];

  for (var player in listPlayers) {
    // add the player
    await playersBox.add(player);
    
    // Get the auto-increment key that was generated
    player.idPlayer = player.key as int;

    // Save the player with the auto-increment id that was generated By Hive
    player.save();
  }

  // seed Teams
  List<Team> listTeams = [
    Team(idPlayer1: 0, idPlayer2: 1, surName: 'Les vieux routiers', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 2, surName: 'Domi, Christo', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 3, surName: 'Marcel et Marcel', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 4, surName: 'Domi, Fred', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 5, surName: 'Domi, Drou', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 6, surName: 'Domi, Ti-Ti', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 7, surName: 'Domi, Marco', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 8, surName: 'Domi, Ludo', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 9, surName: 'Max Domi', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 10, surName: 'Domi, Papy', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 2, surName: 'Ricky, Christo', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 3, surName: 'Ricky, Marcel', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 4, surName: 'Ricky, Fred', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 5, surName: 'Ricky, Drou', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 6, surName: 'Ricky, Ti-Ti', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 7, surName: 'Ricky, Marco', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 8, surName: 'Ricky, Ludo', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 9, surName: 'Ricky, Max', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 10, surName: 'Ricky, Papy', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 3, surName: 'Christo, Marcel', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 4, surName: 'Christo, Fred', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 5, surName: 'Christo, Drou', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 6, surName: 'Christo, Ti-Ti', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 7, surName: 'Christo, Marco', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 8, surName: 'Christo, Ludo', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 9, surName: 'Christo, Max', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 10, surName: 'Christo, Papy', deleted: false),
    Team(idPlayer1: 3, idPlayer2: 4, surName: 'Marcel, Fred', deleted: false),
    Team(idPlayer1: 3, idPlayer2: 5, surName: 'Marcel, Drou', deleted: false),
    Team(idPlayer1: 3, idPlayer2: 6, surName: 'Marcel, Ti-Ti', deleted: false),
    Team(idPlayer1: 3, idPlayer2: 7, surName: 'Marcel, Marco', deleted: false),
    Team(idPlayer1: 3, idPlayer2: 8, surName: 'Marcel, Ludo', deleted: false),
    Team(idPlayer1: 3, idPlayer2: 9, surName: 'Marcel, Max', deleted: false),
    Team(idPlayer1: 3, idPlayer2: 10, surName: 'Marcel, Papy', deleted: false),
    Team(idPlayer1: 4, idPlayer2: 5, surName: 'Fred, Drou', deleted: false),
    Team(idPlayer1: 4, idPlayer2: 6, surName: 'Fred, Ti-Ti', deleted: false),
    Team(idPlayer1: 4, idPlayer2: 7, surName: 'Fred, Marco', deleted: false),
    Team(idPlayer1: 4, idPlayer2: 8, surName: 'Fred, Ludo', deleted: false),
    Team(idPlayer1: 4, idPlayer2: 9, surName: 'Fred, Max', deleted: false),
    Team(idPlayer1: 4, idPlayer2: 10, surName: 'Fred, Papy', deleted: false),
    Team(idPlayer1: 5, idPlayer2: 6, surName: 'Drou, Ti-Ti', deleted: false),
    Team(idPlayer1: 5, idPlayer2: 7, surName: 'Drou, Marco', deleted: false),
    Team(idPlayer1: 5, idPlayer2: 8, surName: 'Drou, Ludo', deleted: false),
    Team(idPlayer1: 5, idPlayer2: 9, surName: 'Drou, Max', deleted: false),
    Team(idPlayer1: 5, idPlayer2: 10, surName: 'Drou, Papy', deleted: false),
    Team(idPlayer1: 6, idPlayer2: 7, surName: 'Ti-Ti, Marco', deleted: false),
    Team(idPlayer1: 6, idPlayer2: 8, surName: 'Ti-Ti, Ludo', deleted: false),
    Team(idPlayer1: 6, idPlayer2: 9, surName: 'Ti-Ti, Max', deleted: false),
    Team(idPlayer1: 6, idPlayer2: 10, surName: 'Ti-Ti, Papy', deleted: false),
    Team(idPlayer1: 7, idPlayer2: 8, surName: 'Marco, Ludo', deleted: false),
    Team(idPlayer1: 7, idPlayer2: 9, surName: 'Marco, Max', deleted: false),
    Team(idPlayer1: 7, idPlayer2: 10, surName: 'Marco, Papy', deleted: false),
    Team(idPlayer1: 8, idPlayer2: 9, surName: 'Ludo, Max', deleted: false),
    Team(idPlayer1: 8, idPlayer2: 10, surName: 'Ludo, Papy', deleted: false),
    Team(idPlayer1: 9, idPlayer2: 10, surName: 'Max, Papy', deleted: false),
    Team(idPlayer1: 0, idPlayer2: 0, surName: 'Domi Twice', deleted: false),
    Team(idPlayer1: 1, idPlayer2: 1, surName: 'Ricky Twice', deleted: false),
    Team(idPlayer1: 2, idPlayer2: 2, surName: 'Christo Twice', deleted: false),
    Team(idPlayer1: 3, idPlayer2: 3, surName: 'Marcel Twice', deleted: false),
    Team(idPlayer1: 4, idPlayer2: 4, surName: 'Fred Twice', deleted: false),
    Team(idPlayer1: 5, idPlayer2: 5, surName: 'Drou Twice', deleted: false),
    Team(idPlayer1: 6, idPlayer2: 6, surName: 'Ti-Ti Twice', deleted: false),
    Team(idPlayer1: 7, idPlayer2: 7, surName: 'Marco Twice', deleted: false),
    Team(idPlayer1: 8, idPlayer2: 8, surName: 'Ludo Twice', deleted: false),
    Team(idPlayer1: 9, idPlayer2: 9, surName: 'Max Twice', deleted: false),
    Team(idPlayer1: 10, idPlayer2: 10, surName: 'Papy Twice', deleted: false),    
  ];

  for (var team in listTeams) {
    // add the player
    await teamsBox.add(team);
    
    // Get the auto-increment key that was generated
    team.idTeam = team.key as int;

    // Save the player with the auto-increment id that was generated By Hive
    team.save();
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Darts 101',      
      theme: ThemeData(
        // This is the theme of your application.
        colorScheme:  ColorScheme.fromSeed(seedColor: Colors.blueAccent),        
      ),
      home: const MyHomePage(title: 'Darts 101'),
    );
  }
}

// --- NEW REUSABLE POPUP MENU WIDGET ---
class MainPopupMenu extends StatelessWidget {
  const MainPopupMenu({super.key});

  void _showPrivacyDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Privacy Policy'),
          content: SizedBox(
            // Set a fixed height so the dialog doesn't jump around
            height: MediaQuery.of(context).size.height * 0.6,
            width: double.maxFinite,
            child: Column(
              children: [
                // 1. SCROLLABLE TEXT AREA
                Expanded(
                  child: SingleChildScrollView(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          "Darts 101 is a free, ad-supported app and is intended for use as is.\n\n"
                          "If you choose to use the Darts 101 app, then you agree to the collection and use of information in relation to this policy. The Personal Information collected by Darts 101 is used for improving Darts 101 and will not be shared with anyone except as described in this Privacy Policy.",
                          style: TextStyle(fontSize: 14),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(vertical: 12.0),
                          child: Text("Information Collection and Use",
                              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        ),
                        const Text(
                          "Darts 101 uses third party services that might collect information used to identify you. The privacy policy URLs for the third party service providers used by Darts 101 are shown below:\n",
                        ),
                        // List of services
                        ...['Google Play Services', 'AdMob', 'Fabric', 'Firebase Analytics', 'Crashlytics']
                            .map((service) => Padding(
                                  padding: const EdgeInsets.only(left: 8.0, bottom: 4.0),
                                  child: Text("• $service", style: const TextStyle(fontWeight: FontWeight.w500)),
                                )),
                        const Text(
                          "\nDarts 101 does not require you to provide personally identifiable information, but the above third party services might.",
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(vertical: 12.0),
                          child: Text("Log Data and Error Reporting",
                              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        ),
                        const Text(
                          "Darts 101 collects data through third party products on your device called Log Data, which may include information such as your device's Internet Protocol address, device name, operating system version, the times you use Darts 101, and other statistics.\n\n"
                          "When Darts 101 crashes, the details of the crash are collected by the third party products; such as when the crash occurred, which screen Darts 101 was showing, etc., and this information is used to improve the stability of Darts 101.",
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(vertical: 12.0),
                          child: Text("Cookies",
                              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        ),
                        const Text(
                          "Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.\n\n"
                          "Darts 101 does not directly use \"cookies\" of any type, but the third party libraries used by Darts 101 might use \"cookies\" to collect information.",
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(vertical: 12.0),
                          child: Text("Security",
                              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        ),
                        const Text(
                          "Darts 101 does not directly request, read, collect, transmit nor store any of your Personal Information, but the third party services used by Darts 101 might make use of your Personal Information to provide their services.",
                        ),
                      ],
                    ),
                  ),
                ),
                // 2. FIXED DIVIDER AND BUTTON
                const Divider(thickness: 1, height: 20),
                SizedBox(
                  width: double.infinity,
                  height: 48,
                  child: ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.blueAccent,
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('Close', style: TextStyle(fontSize: 16)),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  void _showInformationDialog(BuildContext context) async {
    // Fetch the real data from the system
    PackageInfo packageInfo = await PackageInfo.fromPlatform();

    String version = packageInfo.version;     // e.g. 1.0.0
    String buildNumber = packageInfo.buildNumber; // e.g. 1

    if (!context.mounted) return;

    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Information'),
          content: SizedBox(
            // Set a fixed height so the dialog doesn't jump around
            height: MediaQuery.of(context).size.height * 0.6,
            width: double.maxFinite,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // 1. SCROLLABLE TEXT AREA LGGDS_144x144.png
                Expanded(
                  child: SingleChildScrollView(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  const Padding(
                                    padding: EdgeInsets.symmetric(vertical: 12.0),
                                    child: Text("This app was created for the LGGDS Darts League\nQuebec City, Canada",
                                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                  ),
                                  Text("Version: $version",
                                    style: TextStyle(fontSize: 14)
                                  ),
                                  Text("Build: $buildNumber",
                                    style: TextStyle(fontSize: 14),
                                  ),
                                  const Padding(
                                    padding: EdgeInsets.symmetric(vertical: 12.0),
                                    child: Text("Latest Changes:",
                                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                  ),
                                  const Text(
                                    "1. First deployment\n",
                                  ),
                                ]
                              ),
                            ),
                            const SizedBox(width: 10), // Space between text and image
                            // THE IMAGE ON THE RIGHT
                            ClipRRect(
                              borderRadius: BorderRadius.circular(8), // Optional: rounded corners
                              child: Image.asset(
                                'assets/png/LGGDS_216x216.png',
                                width: 216, // Adjust size as needed
                                height: 216,
                                fit: BoxFit.cover,
                              ),
                            ),
                          ]
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(vertical: 12.0),
                          child: Text("Artwork Attributions:",
                              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        ),
                        const Text(
                          "Some artworks in this app are used with a license I bought from iconscout.com\n"
                          "The rest of artworks were created by me.",
                        ),
                      ],
                    ),
                  ),
                ),
                // 2. FIXED DIVIDER AND BUTTON
                const Divider(thickness: 1, height: 20),
                SizedBox(
                  width: double.infinity,
                  height: 48,
                  child: ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.blueAccent,
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('Close', style: TextStyle(fontSize: 16)),
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return PopupMenuButton<String>(
      color: Colors.blueAccent,
      iconColor: Colors.white,
      onSelected: (String value) {
        switch (value) {
          case 'main_pop_menu_privacy':
            _showPrivacyDialog(context);
            break;
          case 'main_pop_menu_info':
            _showInformationDialog(context);
            break;          
        }
      },
      itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
        _buildMenuItem('main_pop_menu_info', 'Information'),
        _buildMenuItem('main_pop_menu_privacy', 'Privacy Policy'),
      ],
    );
  }

  PopupMenuItem<String> _buildMenuItem(String value, String text) {
    return PopupMenuItem<String>(
      value: value,
      child: Text(text, style: const TextStyle(color: Colors.white)),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {  
  // Fonction de navigation when a button is pressed
  void _onTileTapped(BuildContext context, String tileText, String tileCode, Color tileColor, Color tileBackgroundColor) {    
    switch (tileCode){
      case 'manage_players':
        Navigator.push(
          context,
          MaterialPageRoute(
            // The manage_players.dart page will be created and shown
            builder: (context) => ManagePlayers(
              tileText: tileText,
              tileColor: tileColor,
              tileBackgroundColor: tileBackgroundColor,
            ),
          ),
        );
        break;

      case 'manage_teams':
        Navigator.push(
          context,
          MaterialPageRoute(
            // The manage_players.dart page will be created and shown
            builder: (context) => ManageTeams(
              tileText: tileText,
              tileColor: tileColor,
              tileBackgroundColor: tileBackgroundColor,
            ),
          ),
        );
        break;

      case 'half_it_game_teams':
        Navigator.push(
          context,
          MaterialPageRoute(
            // The game_selection.dart page will be created and shown in TeamsMode
            builder: (context) => GameSelection(
              tileText: tileText,
              tileColor: tileColor,
              tileBackgroundColor: tileBackgroundColor,
              enuGameMode: GameMode.gameTeams,
              enuGameType: GameType.gameHalfIt,
            ),
          ),
        );
        break;
      
      case 'half_it_game_players':
        Navigator.push(
          context,
          MaterialPageRoute(
            // The game_selection.dart page will be created and shown in PlayersMode
            builder: (context) => GameSelection(
              tileText: tileText,
              tileColor: tileColor,
              tileBackgroundColor: tileBackgroundColor,
              enuGameMode: GameMode.gamePlayers,
              enuGameType: GameType.gameHalfIt,
            ),
          ),
        );
        break;

      case 'team_build_up':
        Navigator.push(
          context,
          MaterialPageRoute(
            // The manage_players.dart page will be created and shown
            builder: (context) => GameSelection(
              tileText: tileText,
              tileColor: tileColor,
              tileBackgroundColor: tileBackgroundColor,
              enuGameMode: GameMode.gamePlayers,
              enuGameType: GameType.gameBuildUp,
            ),
          ),
        );
        break;

      default:
        ScaffoldMessenger.of(context).hideCurrentSnackBar();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('$tileText was clicked!'),
            duration: const Duration(milliseconds: 800),
          ),
        );
        break;
    }
  }  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blueAccent,        
        title: Row (
          children: [
            // pour l'icone de l'Application
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: SizedBox(
                width: 48.0,
                height: 48.0,
                child: Image.asset(
                  'assets/png/darts_101_logo_48x48.png', // Replace with your image path (PNG, JPG, or SVG)
                  fit: BoxFit.contain, // Ensures the image fits within the box
                ),
              ),
            ),
            // pour le titre de l'Application
            Text(
              widget.title,              
              style: TextStyle(
                color: Colors.white,
              ),
            ),
          ]          
        ),
        actions: const [
          MainPopupMenu(), // Cleanly calling the extracted widget
        ],
      ),
      // The body starts right under the AppBar
      body: Column(
        // Set the Column's main axis size to min to keep it tight, 
        // or leave it at default (max) if you want the buttons at the top.
        mainAxisSize: MainAxisSize.max, 
        
        // Use padding to separate the buttons from the edges
        children: <Widget>[
          // Optional: Add a small separator line under the AppBar
          const Divider(height: 1, thickness: 1),

          // --- Clickable Zone 1 ---
          _buildDarts101Tile(
            context,
            tileText: 'New Players Half-It Game',
            tileCode: 'half_it_game_players',
            tileImageAsset: 'assets/png/dartboard_player_48x48.png',
            tileColor: Colors.lightBlue.shade400,
            tileBackgroundColor: Colors.lightBlue.shade200,
          ),

          // --- Clickable Zone 2 ---
          _buildDarts101Tile(
            context,
            tileText: 'New Teams Half-It Game',
            tileCode: 'half_it_game_teams',
            tileImageAsset: 'assets/png/dartboard_team_48x48.png',
            tileColor: Colors.green.shade400,
            tileBackgroundColor: Colors.green.shade200,
          ),
          
          // --- Clickable Zone 3 ---
          _buildDarts101Tile(
            context,
            tileText: 'Team build up',
            tileCode: 'team_build_up',
            tileImageAsset: 'assets/png/team_build_up_48x48.png',
            tileColor: Colors.grey.shade700,
            tileBackgroundColor: Colors.grey.shade400,
          ),

          // --- Clickable Zone 4 ---
          _buildDarts101Tile(
            context,
            tileText: 'Manage Players',
            tileCode: 'manage_players',
            tileImageAsset: 'assets/png/darts_player_48x48.png',
            tileColor: Colors.deepOrange.shade400,
            tileBackgroundColor: Colors.deepOrange.shade200,
          ),
          
          // --- Clickable Zone 5 ---
          _buildDarts101Tile(
            context,
            tileText: 'Manage Teams',
            tileCode: 'manage_teams',
            tileImageAsset: 'assets/png/darts_team_48x48.png',
            tileColor: Colors.red.shade900,
            tileBackgroundColor: Colors.red.shade400,
          ), 

          // --- Clickable Zone 6 ---
          /* _buildDarts101Tile(
            context,
            tileText: 'Statistics',
            tileCode: 'stats',
            tileImageAsset: 'assets/png/statistics_48x48.png',
            tileColor: Colors.purple.shade400,
          ), */
          
          // Use a Spacer to push the rest of the content (if any) to the bottom
          // If you want the tiles to take up the full width, you don't need a Spacer here.
          const Spacer(),
        ],
      ),
      
    );
  }
  
  // Custom Widget Builder for consistent Tile look
  Widget _buildDarts101Tile(
      BuildContext context, {
      required String tileCode,
      required String tileText,
      required String tileImageAsset,
      required Color tileColor,
      required Color tileBackgroundColor,
  }) {
    return InkWell( // InkWell provides a beautiful ripple effect on tap
      onTap: () => _onTileTapped(context, tileText, tileCode, tileColor, tileBackgroundColor),
      child: Container(
        width: double.infinity, // Ensures the tile fills the width
        padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
        margin: const EdgeInsets.only(bottom: 1.0), // Small line separator
        decoration: BoxDecoration(
          color: tileColor,
          border: Border(
            bottom: BorderSide(color: Colors.white, width: 1),
          ),
        ),
        child: Row(
          children: [
            Image.asset(tileImageAsset),
            const SizedBox(width: 16.0),
            Text(
              tileText,
              style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: Colors.white),
            ),
            const Spacer(),
            const Icon(Icons.arrow_forward_ios, size: 16, color: Colors.white),
          ],
        ),
      ),
    );
  }
}
