import 'package:hive_ce_flutter/hive_ce_flutter.dart';
import 'package:darts_101/global_be.dart';
import 'package:darts_101/database/player.dart';
import 'package:darts_101/database/team.dart';

Future<void> seedHivePlayers(Box<Player> playersBox) async {
  // seed Players
  List<Player> listPlayers = [
    Player(idPlayer: 0, firstName: 'Dominique', lastName: 'Goudreault', nickName: 'Domi', deleted: false),
    Player(idPlayer: 1, firstName: 'Éric', lastName: 'St-Pierre', nickName: 'Ricky', deleted: false),
    Player(idPlayer: 2, firstName: 'Christopher', lastName: 'Lafond', nickName: 'Christo', deleted: false),
    Player(idPlayer: 3, firstName: 'Frédéric', lastName: 'Gagnon', nickName: 'Marcel', deleted: false),
    Player(idPlayer: 4, firstName: 'Frederik', lastName: 'Peeters Bélanger', nickName: 'Fred', deleted: false),
    Player(idPlayer: 5, firstName: 'Simon', lastName: 'Drouin', nickName: 'Drou', deleted: false),
    Player(idPlayer: 6, firstName: 'Étienne', lastName: 'Lefrançois', nickName: 'Ti-ti', deleted: false),
    Player(idPlayer: 7, firstName: 'Marc-Olivier', lastName: 'Fortin', nickName: 'Marco', deleted: false),
    Player(idPlayer: 8, firstName: 'Ludovick', lastName: 'Gosselin', nickName: 'Ludo', deleted: false),
    Player(idPlayer: 9, firstName: 'Maxime', lastName: 'Gagnon', nickName: 'Max', deleted: false),
    Player(idPlayer: 10, firstName: 'Michel', lastName: 'Deschênes', nickName: 'Papy', deleted: false),
    Player(idPlayer: 11, firstName: 'Charles', lastName: 'Lirette', nickName: 'Charles', deleted: false),
    Player(idPlayer: 12, firstName: 'Bryan', lastName: 'Bryan', nickName: 'Bryan', deleted: false),
    Player(idPlayer: 13, firstName: 'Carl', lastName: 'Girard', nickName: 'Carl', deleted: false),
    Player(idPlayer: 14, firstName: 'Carmel', lastName: 'Fortin', nickName: 'Carmel', deleted: false),
  ];

  for (var player in listPlayers) {
    // add the player with the auto-increment key that was generated
    player.idPlayer = await playersBox.add(player);
    
    // Save the player with the auto-increment id that was generated By Hive
    await player.save();
  }
}

Future<void> seedHiveTeams(Box<Player> playersBox, Box<Team> teamsBox) async {
  // Grab all saved players from Hive
  final players = playersBox.values.toList();

  // Dynamically Generate Unique Teams & Self Teams ---
  for (int i = 0; i < players.length; i++) {
    for (int j = i; j < players.length; j++) {
      final p1 = players[i];
      final p2 = players[j];

      // Format surName based on whether it's a self-team or normal team
      final String teamName = (i == j)
          ? '${p1.nickName} Twice'
          : '${p1.nickName}, ${p2.nickName}';

      final team = Team(
        idPlayer1: p1.idPlayer!,
        idPlayer2: p2.idPlayer!,
        surName: teamName,
        deleted: false,
      );

      team.idTeam = await teamsBox.add(team);
      await team.save();
    }
  }  
}

String getPrivacyPolicySection(int section) {
  switch (section) {
    case 1:      
      return "Darts 101 is a free, ad-supported app and is intended for use as is.\n\n"
             "If you choose to use the Darts 101 app, then you agree to the collection and use of information in relation to this policy. The Personal Information collected by Darts 101 is used for improving Darts 101 and will not be shared with anyone except as described in this Privacy Policy.";
    case 2:
      return "Darts 101 uses third party services that might collect information used to identify you. The privacy policy URLs for the third party service providers used by Darts 101 are shown below:\n";
    case 3:
      return "\nDarts 101 does not require you to provide personally identifiable information, but the above third party services might.";
    case 4:
      return "Darts 101 collects data through third party products on your device called Log Data, which may include information such as your device's Internet Protocol address, device name, operating system version, the times you use Darts 101, and other statistics.\n\n"
             "When Darts 101 crashes, the details of the crash are collected by the third party products; such as when the crash occurred, which screen Darts 101 was showing, etc., and this information is used to improve the stability of Darts 101.";
    case 5:
      return "Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.\n\n"
             "Darts 101 does not directly use \"cookies\" of any type, but the third party libraries used by Darts 101 might use \"cookies\" to collect information.";
    case 6:
      return "Darts 101 does not directly request, read, collect, transmit nor store any of your Personal Information, but the third party services used by Darts 101 might make use of your Personal Information to provide their services.";
    default:
      return "";
  }
}

String getInformationSection(int section) {
  switch (section) {
    case 1:
      return "This app was created for :\nThe LGGDS Darts League\nStoneham-et-Tewkesbury, Quebec\nCanada";
    case 2:      
      return "1. First deployment\n";
    case 3:
      return "Some artworks in this app are used with a license I bought from iconscout.com\n"
             "The rest of artworks were created by me.";
    default:
      return "";
  }
}

class InfoDialogImgCfg {
  final String assetPath;
  final double renderSize;

  const InfoDialogImgCfg({required this.assetPath, required this.renderSize});
}

// Returns image configuration based on screen width
InfoDialogImgCfg getInformationDialogImageConfig() {  
  switch (AppDisplay.displayMode) {
    case DisplayMode.display05SmallPhone:
      // Landscape Small/Narrow Phones
      return const InfoDialogImgCfg(
        assetPath: 'assets/png/LGGDS_180x180.png',
        renderSize: 180,
      );

    case DisplayMode.display10CompactPhone:
      // Landscape Phones / Compact Tablets
      return const InfoDialogImgCfg(
        assetPath: 'assets/png/LGGDS_360x360.png',
        renderSize: 360,
      );

    case DisplayMode.display15MediumTablet:
      // 10"-11" Landscape Tablets (Your Galaxy Tab S10 Lite @ 1024dp)
      return const InfoDialogImgCfg(
        assetPath: 'assets/png/LGGDS_512x512.png',
        renderSize: 512,
      );

    case DisplayMode.display20LargeLapDesk:
      // Laptops & Desktop Displays
      return const InfoDialogImgCfg(
        assetPath: 'assets/png/LGGDS_720x720.png',
        renderSize: 720,
      );

    case DisplayMode.display25Ultra4K:
      // 4K & Ultra-wide Displays
      return const InfoDialogImgCfg(
        assetPath: 'assets/png/LGGDS_1000x1000.png',
        renderSize: 1000,
      );
  }
}