import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:darts_101/database/player.dart';

enum FormMode{
  formAdd,
  formModify
}

enum TextType{
  title,
  button,
  icon
}

class ModifyAddPlayerForm extends StatefulWidget {  
  final FormMode enuFormMode;
  final Player? modifyPlayer;

  const ModifyAddPlayerForm({
    super.key,
    required this.enuFormMode,
    this.modifyPlayer,
  });

  @override
  // ignore: library_private_types_in_public_api
  _ModifyAddPlayerFormState createState() => _ModifyAddPlayerFormState();
}

class _ModifyAddPlayerFormState extends State<ModifyAddPlayerForm> {
  final _formKey = GlobalKey<FormState>();

  // Controllers to retrieve text values
  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _nickNameController = TextEditingController();

  // 2. Clean up controllers when the widget is destroyed
  @override
  void dispose() {
    _firstNameController.dispose();
    _lastNameController.dispose();
    _nickNameController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    // If we are modifying, fill the controllers with existing data
    if (widget.enuFormMode == FormMode.formModify && widget.modifyPlayer != null) {
      _firstNameController.text = widget.modifyPlayer!.firstName;
      _lastNameController.text = widget.modifyPlayer!.lastName;
      _nickNameController.text = widget.modifyPlayer!.nickName;
    }
  }

  String _getTextByMode(TextType textType) {
    final isAdd = widget.enuFormMode == FormMode.formAdd;

    switch (textType){
      case TextType.title:  return isAdd ? 'Add a player' : 'Modify a player';
      case TextType.button: return isAdd ? 'Add Player' : 'Modify Player';
      case TextType.icon:   return isAdd ? 'assets/png/add2_36x36.png' : 'assets/png/edit_24x24.png';
    }    
  }

  void _savePlayer() {
    if (_formKey.currentState!.validate()) {      
      // Get the playersBox from Hive
      final playersBox = Hive.box<Player>('playersBox');

      if (widget.enuFormMode == FormMode.formAdd){
        // Create the player object
        final player = Player(
          firstName: _firstNameController.text.trim(),
          lastName: _lastNameController.text.trim(),
          nickName: _nickNameController.text.trim(),
          deleted: false,
        );

        // Add to Hive        
        playersBox.add(player);

        // Get the auto-increment key that was generated
        player.idPlayer = player.key as int;

        // Save the player with the auto-increment id that was generated By Hive
        player.save();

      } else {
          widget.modifyPlayer?.firstName = _firstNameController.text.trim();
          widget.modifyPlayer?.lastName = _lastNameController.text.trim();
          widget.modifyPlayer?.nickName = _nickNameController.text.trim();

          // Save to Hive        
          widget.modifyPlayer?.save();
      }
            
      // Return to previous screen
      Navigator.pop(context);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      //pour le background color en bas du titre et pour le reste de la page
      backgroundColor: Colors.deepOrange.shade200,
      appBar: AppBar(        
        foregroundColor: Colors.white,
        backgroundColor: Colors.deepOrange.shade400,
        
        // pour le titre et l'icone de l'Application        
        title: Row (
          children: [
            // pour l'icone de l'Application
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: SizedBox(
                width: 48.0,
                height: 48.0,
                child: Image.asset(
                  'assets/png/darts_101_logo_48x48.png', // Replace with your image path (PNG, JPG, or SVG)
                  fit: BoxFit.contain, // Ensures the image fits within the box
                ),
              ),
            ),
            // pour le titre de la tuile
            Text(
              _getTextByMode(TextType.title),              
              style: const TextStyle(color: Colors.white),
            ),
          ]          
        ),
      ),
      body: Form(
        key: _formKey,
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            children: [
              _buildTextField(_firstNameController, 'First Name'),
              const SizedBox(height: 10),
              _buildTextField(_lastNameController, 'Last Name'),
              const SizedBox(height: 10),
              _buildTextField(_nickNameController, 'Nickname'),
              const SizedBox(height: 20),
              FloatingActionButton.extended(
                backgroundColor: Colors.deepOrange.shade400,
                label: Text(_getTextByMode(TextType.button), style: const TextStyle(color: Colors.white)),
                icon: Image.asset(_getTextByMode(TextType.icon)),
                onPressed: _savePlayer,               
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField(TextEditingController controller, String label) {
    return TextFormField(
      controller: controller,      
      textCapitalization: TextCapitalization.words,
      // Improves UX: Shows "Next" on keyboard until the last field
      textInputAction: label == 'Nickname' ? TextInputAction.done : TextInputAction.next,
      decoration: InputDecoration(
        labelText: label, 
        filled: true,
        fillColor: Colors.white,
        border:  UnderlineInputBorder(borderRadius: BorderRadius.circular(8)),
      ),
      validator: (value) {
        if ((label == 'Nickname') && (value == null || value.trim().isEmpty)) {
          return '$label is required';
        }
        return null;
      },
    );
  }
}